import { z } from "zod";
import { ConvexTool } from "./index.js";
import { loadSelectedDeploymentCredentials } from "../../api.js";
import { parseArgs, parseFunctionName, runSystemQuery } from "../../run.js";
import { readProjectConfig } from "../../config.js";
import {
  ConvexHttpClient,
  UserIdentityAttributes,
} from "../../../../browser/index.js";
import { Value } from "../../../../values/index.js";
import { DefaultLogger } from "../../../../browser/logging.js";
import { getDeploymentSelection } from "../../deploymentSelection.js";

type FunctionType = "Query" | "Mutation" | "Action" | "HttpAction";

const userSchema = z
  .object({
    subject: z.string().describe("User identifier from the identity provider"),
    issuer: z
      .string()
      .optional()
      .describe(
        "Hostname of the identity provider (defaults to 'https://<deployment>.convex.site')",
      ),
  })
  .describe(
    "Run the function as this user (for testing authenticated functions)",
  );

const inputSchema = z.object({
  functionName: z
    .string()
    .describe(
      "The name of the function to run (e.g. 'path/to/my/module.js:myFunction').",
    ),
  args: z
    .string()
    .describe(
      "The argument object to pass to the function, JSON-encoded as a string.",
    ),
  user: userSchema.optional(),
  deployment: z
    .enum(["dev", "prod"])
    .optional()
    .describe(
      "Target deployment: 'dev' or 'prod'. Defaults to 'dev'. Running mutations/actions on prod requires --dangerously-enable-production-mutations flag.",
    ),
});

const outputSchema = z.object({
  result: z.any().describe("The result returned by the function"),
  logLines: z
    .array(z.string())
    .describe("The log lines generated by the function"),
});

const description = `
Run a Convex function (query, mutation, or action) on your deployment.

Returns the result and any log lines generated by the function.
`.trim();

export const RunTool: ConvexTool<typeof inputSchema, typeof outputSchema> = {
  name: "run",
  description,
  inputSchema,
  outputSchema,
  handler: async (ctx, args) => {
    const { projectDir, deployment } = ctx.resolveDeployment(args.deployment);

    process.chdir(projectDir);
    const metadata = await getDeploymentSelection(ctx, ctx.options);
    const credentials = await loadSelectedDeploymentCredentials(
      ctx,
      metadata,
      deployment,
    );
    const parsedArgs = await parseArgs(ctx, args.args);
    const { projectConfig } = await readProjectConfig(ctx);
    const parsedFunctionName = await parseFunctionName(
      ctx,
      args.functionName,
      projectConfig.functions,
    );

    // Only block mutations and actions on production, not queries
    if (deployment.kind === "prod") {
      const functionType = await getFunctionType(
        ctx,
        credentials.url,
        credentials.adminKey,
        parsedFunctionName,
      );
      if (functionType !== "Query") {
        await ctx.assertProductionMutationsEnabled();
      }
    }

    const logger = new DefaultLogger({ verbose: true });
    const logLines: string[] = [];
    logger.addLogLineListener((level, ...args) => {
      logLines.push(`${level}: ${args.join(" ")}`);
    });
    const client = new ConvexHttpClient(credentials.url, {
      logger: logger,
    });

    // Build user identity if provided
    let identity: UserIdentityAttributes | undefined;
    if (args.user) {
      // Default issuer to the deployment's site URL
      const defaultIssuer = credentials.deploymentFields?.deploymentName
        ? `https://${credentials.deploymentFields.deploymentName}.convex.site`
        : "https://convex.test";
      identity = {
        subject: args.user.subject,
        issuer: args.user.issuer ?? defaultIssuer,
      };
    }
    client.setAdminAuth(credentials.adminKey, identity);
    let result: Value;
    try {
      result = await client.function(parsedFunctionName, undefined, parsedArgs);
    } catch (err) {
      return await ctx.crash({
        exitCode: 1,
        errorType: "invalid filesystem or env vars",
        printedMessage: `Failed to run function "${args.functionName}":\n${(err as Error).toString().trim()}`,
      });
    }
    return {
      result,
      logLines,
    };
  },
};

async function getFunctionType(
  ctx: Parameters<typeof runSystemQuery>[0],
  deploymentUrl: string,
  adminKey: string,
  functionName: string,
): Promise<FunctionType | null> {
  const functions = (await runSystemQuery(ctx, {
    deploymentUrl,
    adminKey,
    functionName: "_system/cli/modules:apiSpec",
    componentPath: undefined,
    args: {},
  })) as (
    | { functionType: FunctionType; identifier: string }
    | { functionType: "HttpAction" }
  )[];

  for (const fn of functions) {
    if (fn.functionType === "HttpAction") continue;
    if (fn.identifier === functionName) {
      return fn.functionType;
    }
  }

  // Function not found - let execution proceed and fail with proper error
  return null;
}
